ALTER TABLE trips ADD COLUMN date DATE NULL;
ALTER TABLE trips ADD COLUMN time VARCHAR(10) NULL;
ALTER TABLE trips ADD COLUMN note TEXT NULL;
ALTER TABLE trips ADD COLUMN createdAt DATETIME DEFAULT CURRENT_TIMESTAMP;
