-- Create Users Table
CREATE TABLE IF NOT EXISTS doorprize_users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL
);

-- Seed Default Users (Password hashes for: @srp4sshadiah@ and @srp4sspimpinan@)
INSERT INTO doorprize_users (username, password, role) VALUES 
('admindoorprz', '$2y$10$YourHashedPasswordHere...', 'admin'),
('pimpinan', '$2y$10$YourHashedPasswordHere...', 'pimpinan');
-- Note: The actual hashes are generated by PHP's password_hash() function.
